# .github/workflows/deploy-pages.yml
name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch (e.g., master)
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Or a newer LTS version
          cache: 'npm'

      - name: Install dependencies
        run: npm ci # Faster and more reliable than 'npm install' for CI

      - name: Build static site and blog
        run: npm run build # This executes 'node generate-blog.js'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site # The directory your build script outputs to

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4